version: 2

updates:
  - package-ecosystem: "docker"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: "pip"
    target-branch: "main"
    directories:
      - /pytests/*
    schedule:
      interval: "daily"
    commit-message:
      prefix: chore
      include: scope
    groups:
      deps:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    target-branch: "main"
    directories:
      - /
      - /wasm
    schedule:
      interval: "daily"
    commit-message:
      prefix: chore
      include: scope
