
## For the full reference, go to (TODO put link)

## You can use another TOML file to extend from.
## For a single file extension:

# extends = "./base.toml"

## Or, for a chain of extensions:

# extends = ["base-1.toml", "base-2.toml"]

chain = "00000000-0000-0000-0000-000000000000"
public_key = "ed0120A98BAFB0663CE08D75EBD506FEC38A84E576A7C9B0897693ED4B04FD9EF2D18D"
private_key = "802620A4DFC16789FBF9A588525E4AC7F791AC51B12AEE8919EACC03EB2FC31D32C692"

trusted_peers = ["ed0120A98BAFB0663CE08D75EBD506FEC38A84E576A7C9B0897693ED4B04FD9EF2D18D@localhost:1337"]

[genesis]
public_key = "ed01204164BF554923ECE1FD412D241036D863A6AE430476C898248B8237D77534CFC4"
# file =

[network]
address = "0.0.0.0:1337"
public_address = "localhost:1337"
# block_gossip_period_ms = 10_000
# block_gossip_size = 4
# transaction_gossip_period_ms = 1_000
# transaction_gossip_size = 500
# idle_timeout_ms = 60_000

[torii]
address = "0.0.0.0:8080"
# max_content_len = 16_000_000
# query_idle_time_ms = 30_000
# query_store_capacity = 128
# query_store_capacity_per_user = 128

[kura]
# init_mode = "strict"
# store_dir = "./storage"
# blocks_in_memory = 128

[logger]
# level = "INFO"
# format = "full"

## Transactions Queue
[queue]
# capacity = 65536
# capacity_per_user = 65536
# transaction_time_to_live_ms = 86_400_000 # 1 day

[snapshot]
# mode = "read_write"
# create_every_ms = 60_000
# store_dir = "./storage/snapshot"

# [telemetry]
# name =
# url =
# min_retry_period_ms = 1_000
# max_retry_delay_exponent = 4

[dev_telemetry]
## A path to a file with JSON logs
# out_file = "./dev_telemetry.json"
