## For the full reference, go to (TODO put link)

## You can use another TOML file to extend from.
## For a single file extension:

# extends = "./base.toml"

## Or, for a chain of extensions:

# extends = ["base-1.toml", "base-2.toml"]

# chain =
# public_key =
# private_key =

# trusted_peers =

[genesis]
# public_key =
# file =

[network]
# address =
# block_gossip_period_ms = 10_000
# block_gossip_size = 4
# transaction_gossip_period_ms = 1_000
# transaction_gossip_size = 500
# idle_timeout_ms = 60_000

[torii]
# address =
# max_content_len = 16_000_000
# query_idle_time_ms = 30_000
# query_store_capacity = 128
# query_store_capacity_per_user = 128

[kura]
# init_mode = "strict"
# store_dir = "./storage"
# blocks_in_memory = 128

[logger]
# level = "INFO"
# format = "full"

## Transactions Queue
[queue]
# capacity = 65536
# capacity_per_user = 65536
# transaction_time_to_live_ms = 86_400_000 # 1 day

[snapshot]
# mode = "read_write"
# create_every_ms = 60_000
# store_dir = "./storage/snapshot"

[telemetry]
# name =
# url =
# min_retry_period_ms = 1_000
# max_retry_delay_exponent = 4

[dev_telemetry]
## A path to a file with JSON logs
# out_file = "./dev_telemetry.json"
