[package]
name = "executor_custom_data_model"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[dependencies]
iroha_executor_data_model.workspace = true
iroha_data_model.workspace = true
iroha_schema.workspace = true

serde_json.workspace = true
serde.workspace = true
