[package]
name = "iroha_schema_gen"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[lints]
workspace = true

[dependencies]
iroha_data_model = { workspace = true, features = ["http", "transparent_api"] }
iroha_executor_data_model = { workspace = true }
iroha_multisig_data_model = { workspace = true }

iroha_primitives = { workspace = true }
iroha_genesis = { workspace = true }
iroha_crypto = { workspace = true }
iroha_schema = { workspace = true }
