name: I2::Dev::Static

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.rs'
      - '**.json'
      - '**.toml'
      - '.github/workflows/iroha2-dev-pr-static.yml'
      - '**.py'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_COMPOSE_PATH: defaults

jobs:
  smart_contracts_analysis:
    runs-on: ubuntu-latest
    container:
      image: hyperledger/iroha2-ci:nightly-2024-09-09
    steps:
      - uses: actions/checkout@v4
      - name: cargo fmt (wasm)
        working-directory: wasm
        run: cargo fmt --all -- --check

  python_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: hyperledger/iroha2-ci:nightly-2024-09-09
    strategy:
      matrix:
        suite: [ iroha_cli_tests, iroha_torii_tests ]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies using Poetry for pytests/${{ matrix.suite }}
        working-directory: pytests/${{ matrix.suite }}
        run: |
          poetry lock --no-update
          poetry install
      - name: Check code formatting with Black in pytests/${{ matrix.suite }}
        working-directory: pytests/${{ matrix.suite }}
        run: |
          poetry run black --check .
      - name: Run mypy (Type Checker) in pytests/${{ matrix.suite }}
        working-directory: pytests/${{ matrix.suite }}
        run: |
          poetry run mypy --explicit-package-bases --ignore-missing-imports .
      - name: Run flake8 (Linter) in pytests/${{ matrix.suite }}
        working-directory: pytests/${{ matrix.suite }}
        run: |
          poetry run flake8 . --max-line-length=110 --ignore=F401,W503,E203
